[workspace]
resolver = "3"
members = [
  "app",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
clap = { version = "4.5.54", features = ["derive"] }
eframe = "0.33"
egui_commonmark = "0.22"
env_logger = "0.11.8"
log = "0.4.29"
logging-options = "0.1.0"
derive-new = "0.7.0"
