[package]
name = "exocortex-page"
version = "0.1.0"
edition.workspace = true

[dependencies]
aliri_braid.workspace = true
derive_more = { workspace = true, features = ["from"] }
derive-new.workspace = true
thiserror.workspace = true
include_dir.workspace = true
